//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriterUnderContract : Writer
    {
        public int Salary { get; set; }
        public int NumWorkHours { get; set; }
    
        public virtual Magazine Magazine { get; set; }
    }
}
