//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrittenPublication
    {
        public int Id { get; set; }
        public int WriterId { get; set; }
        public int PublicationId { get; set; }
    
        public virtual Writer Writer { get; set; }
        public virtual Field Field { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
